-- Agent 表
CREATE TABLE IF NOT EXISTS agent (
    id BIGINT PRIMARY KEY,
    name VARCHAR(100) NOT NULL COMMENT 'Agent 名称',
    type VARCHAR(50) NOT NULL COMMENT 'Agent 类型',
    status VARCHAR(20) DEFAULT 'ACTIVE' COMMENT '状态：ACTIVE, INACTIVE, BUSY',
    endpoint VARCHAR(255) COMMENT '端点地址',
    task_count INT DEFAULT 0 COMMENT '任务数量',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted INT DEFAULT 0 COMMENT '逻辑删除：0-未删除，1-已删除'
);
